In [1]:
print(list(range(5)))

[0, 1, 2, 3, 4]


In [ ]:
output_list = []
row_list = []
numRows = 5

for i in range(numRows):
    if i == 0:
        row_list.append(i+1)
        output_list.append(row_list)
    if i == 1:
        row_list = []
        row_list.append(i)
        row_list.append(i)
        output_list.append(row_list)
    if i > 1:
        row_list_curr = [1, sum(row_list), 1]
        output_list.append(row_list_curr)
        row_list_curr = []

In [12]:
from typing import List

class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        output_list = []
        row_list = []
        for i in range(numRows):
            if i == 0:
                row_list.append(i+1)
                output_list.append(row_list)
            if i == 1:
                row_list = []
                row_list.append(i)
                row_list.append(i)
                output_list.append(row_list)
                row_list = []
        return output_list

solution = Solution()
numRows = 2
solution.generate(numRows)

[[1], [1, 1]]

In [18]:
import numpy as np

c = np.zeros((5, 5))
print(c)



[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [32]:
7*[1]

[1, 1, 1, 1, 1, 1, 1]

In [33]:
numRows = 5
numRows * [1]

[1, 1, 1, 1, 1]

In [35]:
numRows = 5
c = [[1], [1, 1]]
for i in range(2, numRows):
    c.append((i+1) * [1])
    for j in range(1, i):
        c[i][j] = c[i-1][j-1] + c[i-1][j]

print(c)

[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]


In [36]:
from typing import List

class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        c = [[1], [1, 1]]
        for i in range(2, numRows):
            c.append((i+1) * [1])
            for j in range(1, i):
                c[i][j] = c[i-1][j-1] + c[i-1][j]

        return c

solution = Solution()
numRows = 5
solution.generate(numRows)

[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]

### First submission
Could be time optimized

Accepted by LeetCode: Runtime: 32 ms, faster than 34.37% of Python3 online submissions for Pascal's Triangle.  
Memory Usage: 13.8 MB, less than 7.14% of Python3 online submissions for Pascal's Triangle.

In [7]:
from typing import List

class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        if numRows == 0:
            return []

        c = [[1]]
        for i in range(1, numRows):
            c.append((i+1) * [1])
            for j in range(1, i):
                c[i][j] = c[i-1][j-1] + c[i-1][j]

        return c

solution = Solution()
numRows = 5
# numRows = 0
# numRows = 1
solution.generate(numRows)

[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]

### Second submission

Accepted by LeetCode: Runtime: 28 ms, faster than 68.76% of Python3 online submissions for Pascal's Triangle.  
Memory Usage: 13.8 MB, less than 7.14% of Python3 online submissions for Pascal's Triangle.

In [13]:
class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        if numRows == 0:
            return []

        c = [(i+1)*[1] for i in range(numRows)]

        for i in range(numRows):
            for j in range(1, i):
                c[i][j] = c[i-1][j-1] + c[i-1][j]

        return c

solution = Solution()
numRows = 5
# numRows = 0
# numRows = 1
solution.generate(numRows)

[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]